/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ErrorBoundary: (typeof import("./app/root"))["ErrorBoundary"];
  const I18nProvider: (typeof import("@lingui/react"))["I18nProvider"];
  const Layout: (typeof import("./app/root"))["Layout"];
  const Links: (typeof import("react-router"))["Links"];
  const Meta: (typeof import("react-router"))["Meta"];
  const Outlet: (typeof import("react-router"))["Outlet"];
  const QueryClientProvider: (typeof import("@tanstack/react-query"))["QueryClientProvider"];
  const ReactQueryDevtools: (typeof import("@tanstack/react-query-devtools"))["ReactQueryDevtools"];
  const Route: (typeof import("./+types/root"))["Route"];
  const Scripts: (typeof import("react-router"))["Scripts"];
  const ScrollRestoration: (typeof import("react-router"))["ScrollRestoration"];
  const Trans: (typeof import("@lingui/react"))["Trans"];
  const clientLoader: (typeof import("./app/root"))["clientLoader"];
  const createPortal: (typeof import("react-dom"))["createPortal"];
  const createRef: (typeof import("react"))["createRef"];
  const findDOMNode: (typeof import("react-dom"))["findDOMNode"];
  const forwardRef: (typeof import("react"))["forwardRef"];
  const hydrate: (typeof import("react-dom"))["hydrate"];
  const i18n: (typeof import("@lingui/core"))["i18n"];
  const isRouteErrorResponse: (typeof import("react-router"))["isRouteErrorResponse"];
  const lazy: (typeof import("react"))["lazy"];
  const links: (typeof import("./app/root"))["links"];
  const memo: (typeof import("react"))["memo"];
  const plural: (typeof import("@lingui/macro"))["plural"];
  const queryClient: (typeof import("./lib/react-query"))["queryClient"];
  const render: (typeof import("react-dom"))["render"];
  const root: (typeof import("./app/root"))["default"];
  const routes: (typeof import("./app/routes"))["default"];
  const select: (typeof import("@lingui/macro"))["select"];
  const selectOrdinal: (typeof import("@lingui/macro"))["selectOrdinal"];
  const startTransition: (typeof import("react"))["startTransition"];
  const t: (typeof import("@lingui/macro"))["t"];
  const unmountComponentAtNode: (typeof import("react-dom"))["unmountComponentAtNode"];
  const useCallback: (typeof import("react"))["useCallback"];
  const useContext: (typeof import("react"))["useContext"];
  const useDebugValue: (typeof import("react"))["useDebugValue"];
  const useDeferredValue: (typeof import("react"))["useDeferredValue"];
  const useEffect: (typeof import("react"))["useEffect"];
  const useId: (typeof import("react"))["useId"];
  const useImperativeHandle: (typeof import("react"))["useImperativeHandle"];
  const useInsertionEffect: (typeof import("react"))["useInsertionEffect"];
  const useLayoutEffect: (typeof import("react"))["useLayoutEffect"];
  const useMemo: (typeof import("react"))["useMemo"];
  const useReducer: (typeof import("react"))["useReducer"];
  const useRef: (typeof import("react"))["useRef"];
  const useState: (typeof import("react"))["useState"];
  const useSyncExternalStore: (typeof import("react"))["useSyncExternalStore"];
  const useTransition: (typeof import("react"))["useTransition"];
}
